"use client";

import { useEffect, useState } from "react";
import type { AppManifest } from "@/lib/compose/compose";

/**
 * "… with a picture of mt fuji": the picture the person asked for, generated by Gemini via /api/image.
 * Each URL is cached forever by the CDN and the browser, so a picture is generated once per prompt.
 */

/** pending = not requested yet (Start-menu preview: never generate per keystroke). */
export type AppPicture = { subject: string; src: string | null; error: string | null; pending?: boolean };

function styleFor(app: AppManifest) {
  if (/\b(photo|photograph|realistic)\b/i.test(app.prompt)) return "photo";
  if (/\bpixel\b/i.test(app.prompt)) return "pixel";
  return app.shell === "paint" ? "paint" : "default";
}

export function pictureUrl(app: AppManifest): string | null {
  const q = app.params.image;
  return q ? `/api/image?${new URLSearchParams({ q, style: styleFor(app) })}` : null;
}

const done = new Map<string, Promise<string>>();
function load(url: string): Promise<string> {
  let p = done.get(url);
  if (!p) {
    p = fetch(url).then(async (r) => {
      if (!r.ok) throw new Error(((await r.json().catch(() => ({}))) as { error?: string }).error ?? `image ${r.status}`);
      return URL.createObjectURL(await r.blob());
    });
    done.set(url, p);
    p.catch(() => done.delete(url));
  }
  return p;
}

export function usePicture(app: AppManifest, enabled = true): AppPicture | null {
  const url = pictureUrl(app);
  const [state, setState] = useState<{ url: string; src: string | null; error: string | null } | null>(null);
  useEffect(() => {
    if (!url || !enabled) return;
    let ok = true;
    load(url).then(
      (src) => ok && setState({ url, src, error: null }),
      (e) => ok && setState({ url, src: null, error: (e as Error).message }),
    );
    return () => {
      ok = false;
    };
  }, [url, enabled]);
  if (!url || !app.params.image) return null;
  const cur = state?.url === url ? state : null;
  return { subject: app.params.image, src: cur?.src ?? null, error: cur?.error ?? null, pending: !enabled };
}

/** The picture as a Win98 framed panel, for every shell except Paint (which draws it on its canvas). */
export function PictureFrame({ pic, preview }: { pic: AppPicture; preview?: boolean }) {
  const h = preview ? 100 : 160;
  return (
    <div className="sunken" style={{ flex: "none", height: h, marginTop: 3, background: "#fff", display: "flex", alignItems: "center", justifyContent: "center", overflow: "hidden", position: "relative" }}>
      {pic.src ? (
        // eslint-disable-next-line @next/next/no-img-element -- a blob URL from our own /api/image
        <img src={pic.src} alt={pic.subject} style={{ height: "100%", width: "auto", maxWidth: "100%", objectFit: "contain", display: "block" }} />
      ) : (
        <PictureStatus pic={pic} />
      )}
    </div>
  );
}

export function PictureStatus({ pic }: { pic: AppPicture }) {
  return (
    <div style={{ fontSize: 12, color: pic.error ? "#a00" : "#444", padding: 8, textAlign: "center" }}>
      {pic.error ? `Couldn't draw "${pic.subject}": ${pic.error}` : pic.pending ? `🖼️ "${pic.subject}" is drawn when you open the app` : `Drawing "${pic.subject}"…`}
    </div>
  );
}
